name: PerrokEssentials
version: '1.0'
main: fr.pqndaa.perrokEssentials.PerrokEssentials
api-version: '1.21'
authors: [ PQNDAA ]
commands:
  money:
    description: Voir votre argent en temps réel.
    usage: /<command> <joueur>
  broadcast:
    description: Ecrire un message global pour le serveur.
    usage: /<command> <message>
  pay:
    description: Donner de l'argent à un joueur.
    usage: /<command> <joueur> <valeur>
  setspawn:
    description: Mettre en place un spawn sur le serveur.
    usage: /<command>
  spawn:
    description: Se teleporter au spawn du serveur.
    usage: /<command>
  reloadpl:
    description: Redémarrer un plugin spécifique.
    usage: /<command> <plugin>